#ifndef DECODER_RECEIVER_RECEIVER_H_
#define DECODER_RECEIVER_RECEIVER_H_

typedef enum ReceiverStatus {
  RECEIVER_STATUS_ERROR = -1,
  RECEIVER_STATUS_OKAY = 0,
  RECEIVER_STATUS_CLOSED,
} ReceiverStatus_e;

#endif  // __DECODER_RECEIVER_RECEIVER_H
